var app = angular.module("myApp",   [
    'myAppLoginCtrl',
    'myAppRegistrationCtrl',
    'myAppUserService',
    'myAppUserCtrl',
    'myAppHomeCtrl',
    'myAppgameCtrl',
    'myAppGameService',
    'myAppNewPCtrl',
    'myAppPostService',
    'myAppApplicationCtrl',
    'myAppProfileCtrl',
    'myAppConfigCtrl',
    'myAppStoreCtrl',
    'myAppRateCtrl',
    'myAppRouter',
    'myAppNavbarDirective',
    'myAppNavbarService',
    'myAppModeService',
    'myAppPlatformService',
    'myAppReviewService',
    'myAppRewardService',
    'myAppTokenService',
    'myAppPopupService',
    'myAppContact_infService'
]);

